version: "3"
services:

  # Plex
  plex:
    hostname: plex
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    networks:
      - default
      - traefik_proxy
    enviroment:
      - "PLEX_UID=${PUID}""
      - "PLEX_GID=${PGID}"
      - "PLEX_CLAIM=${PLEX_CLAIM}"
      - "ADVERTISE_IP=https://${PLEX_SUBDOMAIN}.${DOMAIN}"
      - "HOME=/config"
    ports:
      - "1900:1900/udp"
      - "3005:3005/tcp"
      - "32400:32400/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:42414/udp"
      - "32469:32469/tcp"
      - "33400:32400/tcp"
      - "33433:33433/tcp"
      - "8324:8324/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:https://${PLEX_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=32400"
      - "traefik.protocol=https"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_servers/plex:/config"
      - "/etc/localtime:/etc/localtime"

  # Jellyfin
  jellyfin:
    hostname: jellyfin
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    networks:
      - default
      - traefik_proxy
    enviroment:
      - "UID=${PUID}"
      - "GID=${PGID}"
    ports:
      - "8096:8096/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:https://${JELLYFIN_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=8096"
      - "traefik.protocol=https"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_servers/jellyfin:/config"
      - "/etc/localtime:/etc/localtime"

  funkwhale:
    hostname: funkwhale
    container_name: funkwhale
    image: funkwhale/all-in-one
    restart: unless-stopped
    env_file: ${BASE_DIR}/media_servers/funkwhale/.env
    networks:
      - traefik_proxy
    enviroment:
      - "PUID=${PUID}"
      - "PGID=${PGID"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:https://${FUNKWHALE_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=80"
      - "traefik.protocol=https"
    volumes:
      - "${BASE_DIR}/media_servers/funkwhale/data:/data"
      - "${MUSIC_PATH}/music:/music"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge