version: "3"
services:
  # Traefik
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAIN}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${TRAEFIK_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BASE_DIR}/services/traefik:/etc/traefik
      - ${BASE_DIR}/docker/shared:/shared

  # Portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_DIR}/services/portainer/data:/data
      - ${BASE_DIR}/shared:/shared
    environment:
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${PORTAINER_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=9000"

  # Speedtest
  speedtest:
    container_name: speedtest
    image: physk/speedtest
    restart: always
    environment:
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${SPEEDTEST_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=80"

  # Netdata
  netdata:
    container_name: netdata
    image: titpetric/netdata
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${NETDATA_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=19999"
  # Dash
  # dash:
  #   image: getholo/dash
  #   container_name: dash
  #   restart: always
  #   privileged: true
  #   volumes:
  #     - /mnt/move:/mnt/move
  #     - ${BASE_DIR}/services/dash:/config
  #     - UNIONFS:/unionfs
    # enviroment:
    #   - TZ=${TZ}
    #   - PUID=${PUID}
    #   - PGID=${PGID}
  #     - MOUNT=true
  #     - TOKEN=${DASH_TOKEN}
  #   network:
  #     - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge