version: "3"
services:

  # Sonarr Adults
  sonarr-adults:
    container_name: sonarr-adults
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${SONARRA_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=8989"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_content/sonarra:/config"
      - "/mnt/nzbget/completed:/completed"
      - "/etc/localtime:/etc/localtime"

  # Sonarr Kids
  sonarr-kids:
    container_name: sonarr-kids
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${SONARRK_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=8989"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_content/sonarrk:/config"
      - "/mnt/nzbget/completed:/completed"
      - "/etc/localtime:/etc/localtime"

  # Radarr Adults
  radarr-adults:
    container_name: radarr-adults
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${RADARRA_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=7878"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_content/radarra:/config"
      - "/mnt/nzbget/completed:/completed"
      - "/etc/localtime:/etc/localtime"

  # Radarr Kids
  radarr-kids:
    container_name: radarr-kids
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${RADARRK_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=7878"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_content/radarra:/config"
      - "/mnt/nzbget/completed:/completed"
      - "/etc/localtime:/etc/localtime"

  # Ombi Adults
  ombi-adults:
    container_name: ombi-adults
    image: linuxserver/ombi
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${OMBIA_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=3579"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "${BASE_DIR}/media_content/ombia:/config"
      - "/etc/localtime:/etc/localtime"

  # Ombi Kids
  ombi-kids:
    container_name: ombi-kids
    image: linuxserver/ombi
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${OMBIK_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=3579"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "${BASE_DIR}/media_content/ombik:/config"
      - "/etc/localtime:/etc/localtime"

  # Mellow Adults
  mellow-adults:
    container_name: mellow-adults
    image: voidp/mellow:latest
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${GUID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${MELLOWA_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=5060"
      - "com.centurylinklabs.watchtower.enable=true"

  # Mellow Kids
  mellow-kids:
    container_name: mellow-kids
    image: voidp/mellow:latest
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${GUID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${MELLOWK_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=5060"
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge