version: "3"
services:
  sonarra:
    container_name: sonarra
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      # - default
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${SONARRA_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=8989"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_content/sonarra:/config"
      - "/mnt/nzbget/completed:/completed"
      - "/etc/localtime:/etc/localtime"
  sonarrk:
    container_name: sonarrk
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      # - default
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${SONARRK_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=8989"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_content/sonarrk:/config"
      - "/mnt/nzbget/completed:/completed"
      - "/etc/localtime:/etc/localtime"
  radarra:
    container_name: radarra
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      # - default
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${RADARRA_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=7878"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_content/radarra:/config"
      - "/mnt/nzbget/completed:/completed"
      - "/etc/localtime:/etc/localtime"
  radarrk:
    container_name: radarrk
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      # - default
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${RADARRK_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=7878"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/mnt/unionfs:/unionfs"
      - "${BASE_DIR}/media_content/radarra:/config"
      - "/mnt/nzbget/completed:/completed"
      - "/etc/localtime:/etc/localtime"
  ombia:
    container_name: ombia
    image: linuxserver/ombi
    restart: unless-stopped
    networks:
      # - default
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${OMBIA_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=3579"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "${BASE_DIR}/media_content/ombia:/config"
      - "${BASE_DIR}/media_content/ombia/appsettings.json:/opt/ombi/appsettings.json"
      - "/etc/localtime:/etc/localtime"
  ombik:
    container_name: ombik
    image: linuxserver/ombi
    restart: unless-stopped
    networks:
      # - default
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${OMBIK_SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=3579"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "${BASE_DIR}/media_content/ombik:/config"
      - "${BASE_DIR}/media_content/ombik/appsettings.json:/opt/ombi/appsettings.json"
      - "/etc/localtime:/etc/localtime"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge